[package]
name = "async_rate_limiter"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tonic-build = "0.11.0"


[dependencies]
prost = "0.12.3"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "sync", "time"] }
tonic = "0.11.0"
